### ISSUE TITLE
how you make an exe????

### ISSUE THREAD

**Issue by webbrowser11** [cWorksLLC/miniorganize#1]

**Comment by BDadmehr0** [comment]
https://www.geeksforgeeks.org/convert-python-script-to-exe-file/ @webbrowser11

**Comment by webbrowser11** [comment]
thanks btw how did you even see this so fast XD i never get this attention on my repos

**Comment by webbrowser11** [comment]
@BDadmehr0

**Comment by BDadmehr0** [comment]
> thanks btw how did you even see this so fast XD i never get this attention on my repos

Hey, no problem!, I was browsing for good issues to contribute to, and this one caught my eye. The solution seemed straightforward (just sharing a link), so I thought I’d help out. Thanks for the kind words! Keep up the great work on your repos!
